### PR TITLE
feat: set actual ΟΞ token bridge dapp link

### PR DESCRIPTION
**Pull request by vbstreetz**

### CODE REVIEW

**Review by JChiaramonte7 — CHANGES_REQUESTED** [review]
Can we change to 'Get wETH' instead of 'Buy wETH'?

And also 'Not enough L2 wETH for transaction fees. Get some via Optimism bridge:'

**Comment by vbstreetz** [comment]
> Can we change to 'Get wETH' instead of 'Buy wETH'?
> 
> And also 'Not enough L2 wETH for transaction fees. Get some via Optimism bridge:'

Gotcha. Pinged you about this on figma.

**Review by JChiaramonte7 — APPROVED** [review]
Sounds good @vbstreetz I'll approve this PR since it's not related to this.

**Comment by vbstreetz** [comment]
> Sounds good @vbstreetz I'll approve this PR since it's not related to this.

Gotcha. Though we can wait since I think @zoe-archer should have gotten back to us by tomorrow?

**Pull request merged**
